server:
  port: 8091

spring:
  application:
    name: AuthService

  rabbitmq:
    host: '{cipher}AQCjdg6NwR/S/RmDt6x3zbxYoV3DdfVB2wvqIoJSIrewFO+6BgFAmQJbfJRPSjOBxHV7Y3UZRmc1J9peMnxoTRSCL8SrwE+6jUfz7f+AkrtycL0TZj8PyhT1Xen4PojnPZwiweGACIsnGNvcZ3yNyEQC334v7qSIjtFSGrYLziJWC94dCPdoe2FyFlPli68ywyDG9UUwijeWVRzlbGxXBYJJTAmikwDqq2m0JjG82Qt7TFxpTasNOWP/FBDWWxxjVquWMPa8qmnO9TUGeYNEMvAn3T4rMnLoUiVZ1s/gw+023xTM4zZ6RMDhqaJqNi+UAVzaAIVghp9s0yS9e8WgxhIGmUA+IWf150r67mtj8pkGW2+siyNn8gjMeYYIB071MNmC6kNCBuMQqnPfrCU1LavEnBPUEtOOUXjCAy05QkL+ajSkuVNFbUv0WTSIXoKNZqs='
    port: 5672
    username: '{cipher}AQBKx0sJKfPqHtwplQyhHdpKQhSON7ENcua4aM2lRdQjgCtw62vn5+YkNA9NYWFGoN4XaqvabhNvUkY7DD5Q0J9hvZ664did1vyRVJBVwE9HrGzJBuURq5Qw3hgs7jcUkPX/kyxMYHfX+Bnj2+5k7ThlfPfpWhKQJbeSmGFhvnI3yf/4PZP2DPj99NJBQ+tfH65MtxW7HxqAx0JWnK7evfXP8BH4BExkPhe4H+hEEos/UR7U6pgLd8cO9BBg9IacMIy4cHNhR3BTh5YJ0mBS2OamOx2Ql5CRBlWFCzHukXjlF2hUSEqd7rlZA9J310kqBcEoxSucjzXEVCG5Y2erNyEeuP2LFoa4Qo/Q+iHPJ4hhCQwoDvmJPCN2+LTWkIFYyJc='
    password: '{cipher}AQA6IJaiuI5FD5hmQbKtcYCvA4+2eaFn95MA5LnHC0EPvlxJCTuK3Rim+k+jfD0lwaJN+17tC2Um929hpGUqw2zvxSMUUQC7y2NiLPS0eW9qKzqaHt0i6DGgsF/dCqHzhysXAn84WK5GKaWT1uwsDlLvJTUA6ErS2EKMux/JpXjQb9EbLVd37BKdkA9tLRGwZaP4iZeM21Xk24KymcJU+nc+mmWhGkWLoTXXhhEyXw6p0eedqHQjsKt2OZvmAbA2skrImXQ2slkIKKeOAvyeycXgMuT7Ww8hn4YvU07v1nW3yPzNtCClN83Hy/gpQDO1MsQyaPcalFZcy+nDPzDvXxMpYe6U9iQV0fnqvAl9P1aIeLJ5A3U7QDhL1+ny7B83ECo='
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

  session:
    store-type: redis
    timeout: 5m
    redis:
      save-mode: on_set_attribute
      flush-mode: on_save

  redis:
    host: '{cipher}AQCAANg2eeqbwmi3tQmaqTTHBJuzKJhrOLeVieMgdWtno8cfC9s380tyzmXFN/L4QD89lc79wI6ifr3ccQOICnOow1W6JDGHBUooG2cXWuCa/gPGa9QBXaOBiqbn32blHkS9iocvyWFpcKI4Lca1bUbSC/n1Bz80OseAs+GJPiysLvDuj3g9ZMODuK45mOX7zYmhLNMOhvGnSoBG82i5BxiLFxMwYunvmnHr9P+e5VACa5VA3YvVzY9BNZ6ebB3ilnhe6GJQxW8R44qDHGbCbKcqr6eOkFO4Xqwa6tuKYEgtGyfZx+ORzekDhLFH1Ubh14nZBrAsMdzrzRjrBY6k9Ybb0tI+ua7QZWkH2vIT2DXI02wgLZO8kbffg5PZ68IxIF6F3Ql9f1Lobf6BxlDLHZJBQoSxYiXQfOK0/3YM3JgwGLW4PUaRAnF8D4w6pUHJ76U='
    port: 6379
    password: '{cipher}AQAz82qbC1B4s9SZ9aUt7naQJWxOKjocPbQergX+49V3hUSYty0pC3PEYs/87RzYIK7vhoyByi9fPrngo8RnnJ5tfB7V5mQMNKzRiyJmSe3jhl4P0nT0whdHOMJjgiYsEzX9Uz/X2rlkFcRg9Kc281dIcF0dCSuMbPYW0r6LO+jMLxz/QmnYkiO5xaC0gC2ky/T6ApnyFhLgm2DXyDRHpZe94CbZYi4eyRUgtjVu/x3K06Ys3ge9UAdWhf6ZfDtCdutifz7PbUPHbSdoKckk/W3MyG7prK9312SRgtgb9cXX3rqHfe8CpaAM3XJqlBQIU88uBAki8LPcjz3cHWZMAVExfr2wzC6udCHShUBNoKqRq940O2Y4AmjMvLw2xdutsHI='

  data:
    mongodb:
      uri: '{cipher}AQCrHvDQu7fnttVVof3jibUcpCmJmrrUkku2gEDWNbD2hqn09W5b9VAE6EY0qrddFOYuKG6cX3+3w106T+vdcIcPWWsZMDoYaeXW7530icMNv9X+8KXj2lvZBCbDCehq+KU5nC4RXFI5vxA3IvYh6JbvePAdAuEZ5SNRXizJpJLxXlZqB5cVI/Zvves09epVIfVDZZrqx81/UbH/gvbgRbGQvMqMYv/b/nkP7zbjWE9WBFJYe+zv2UZgVZp4N8ouAAnCGHLuZO+sNWngqMli/DZs/Gxm4Y7JqYMMqR6v9MFG2kj5ubh9WUxagOxt63ktMsToBJy89BERzgOkymQ/yySXo6tsn0SuSMy3+fElptoakbbgQTXk5HbSO8juyjFixXTKNY7KQ6IjV6Mbxal2YL0aewcyVwoybKIOjt15ARfXcFAYBrJUyr/Z22cRnPTUbESaomDW+zYOjB2KKo8Xvmc0cZULwikIUBSUe5PNJFyvPcWGED/TO+soQR7IDmCbMn4='

eureka:
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone:  "http://eureka:8761/eureka, http://eureka2:8762/eureka"

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}


check:
  response:
    value: "testing if this works"